<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="RLE0131" name="UserProfileBasicTest" tests="1" failures="1" timestamp="4 Jan 2016 11:38:10 GMT" time="0.036" errors="0">
  <testcase name="runTestAssert" time="0.016" classname="com.userprofile.scholastic.test.TestAssert">
    <failure type="java.lang.AssertionError" message="expected [2] but found [4]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [4]
	at com.userprofile.scholastic.test.TestAssert.runTestAssert(TestAssert.java:15)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- runTestAssert -->
</testsuite> <!-- UserProfileBasicTest -->
